version: "3.8"

services:
    app:
        build: .
        container_name: legacy-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    web:
        image: nginx:alpine
        container_name: legacy-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: postgres:15
        container_name: legacy-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: legacy
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:

volumes:
    dbdata:
